version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: subs-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  subs-app:
    image: subs-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data: