definitions:
  domain.Filter:
    properties:
      endDate:
        type: string
      limit:
        type: integer
      offset:
        type: integer
      price:
        type: integer
      serviceName:
        type: string
      startDate:
        type: string
      userID:
        type: string
    type: object
  domain.Subscription:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  domain.SubscriptionInput:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/subscriptions:
    delete:
      consumes:
      - application/json
      description: Удаляет подписку по user_id и service_name
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: user_id and service_name are required
          schema:
            type: string
        "404":
          description: subscription not found
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает список подписок с фильтрами и пагинацией
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - description: Цена
        in: query
        name: price
        type: integer
      - description: Дата начала
        in: query
        name: start_date
        type: string
      - description: Дата конца
        in: query
        name: end_date
        type: string
      - description: Лимит
        in: query
        name: limit
        type: integer
      - description: Смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Subscription'
            type: array
        "500":
          description: internal server error
          schema:
            type: string
      summary: Получить список подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт новую подписку
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/domain.SubscriptionInput'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: error decode
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Создать подписку
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет существующую подписку по ID
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/domain.SubscriptionInput'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error decode
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Обновить подписку
      tags:
      - subscriptions
  /api/subscriptions/summary:
    post:
      consumes:
      - application/json
      description: Возвращает сумму подписок по фильтру
      parameters:
      - description: Фильтр
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/domain.Filter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: invalid filter
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Сводная информация по подпискам
      tags:
      - subscriptions
swagger: "2.0"
